### ISSUE TITLE
Testnet checklist

### ISSUE THREAD

**Issue by assafmo** [enigmampc/SecretNetwork#260]
- [ ] Faucet
- [ ] Stress test a network with X nodes and Y validators for a few days (HW mode)
- [ ] Publish SecretJS to npm
- [ ] Test `.deb` package installation
- [ ] Test docker installation
- [ ] Docs?
- [ ] Register for keys from Intel to compile the Enclave
- [ ] Seal with MRENCLAVE
- [ ] Remote attestation - use the real API
